"""Human-readable output: the PR comment and terminal tables."""

MARKER = "<!-- pr-token-ledger -->"


def fmt_tokens(n):
    n = n or 0
    if n >= 1_000_000:
        return f"{n / 1_000_000:.2f}M"
    if n >= 1_000:
        return f"{n / 1_000:.0f}K"
    return str(n)


def fmt_usd(x):
    return "n/a" if x is None else f"${x:,.2f}"


def cache_rate(r):
    denom = (r.get("input_tok") or 0) + (r.get("cache_write_tok") or 0) + (r.get("cache_read_tok") or 0)
    return f"{100 * (r.get('cache_read_tok') or 0) / denom:.0f}%" if denom else "-"


def total_tokens(r):
    return (r.get("input_tok") or 0) + (r.get("output_tok") or 0) + (r.get("cache_write_tok") or 0) + (r.get("cache_read_tok") or 0)


def pr_comment(rows, meta, pr, dashboard_url=None):
    ticket = f" · {pr['ticket_id']}" if pr and pr.get("ticket_id") else ""
    lines = [MARKER, f"### 🧾 AI usage for this PR{ticket}", "",
             "| model | tokens | cache hit | cost |", "|---|---:|---:|---:|"]
    total_cost = 0.0
    total_tok = 0
    for r in rows:
        lines.append(f"| `{r['model']}` | {fmt_tokens(total_tokens(r))} | {cache_rate(r)} | {fmt_usd(r['cost_usd'])} |")
        total_cost += r["cost_usd"] or 0
        total_tok += total_tokens(r)
    sessions = meta.get("sessions") or 0
    inferred = meta.get("inferred") or 0
    note = f"{sessions} session{'s' if sessions != 1 else ''}" + (f" · {inferred} inferred" if inferred else "")
    lines.append(f"| **total** | **{fmt_tokens(total_tok)}** | | **{fmt_usd(total_cost)}** |")
    lines += ["", f"_{note}. API-equivalent cost at list prices; not what Kikoff is billed. "
                  "Generated by PR Token Ledger from local Claude Code / Codex session metadata — no prompt text leaves the laptop._"]
    if dashboard_url:
        lines.append(f"[Dashboard]({dashboard_url})")
    return "\n".join(lines)


def table(headers, rows):
    widths = [max(len(str(h)), *(len(str(r[i])) for r in rows)) if rows else len(str(h)) for i, h in enumerate(headers)]
    out = ["  ".join(str(h).ljust(w) for h, w in zip(headers, widths))]
    out.append("  ".join("-" * w for w in widths))
    for r in rows:
        out.append("  ".join(str(c).ljust(w) for c, w in zip(r, widths)))
    return "\n".join(out)
